// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDITLtlZ8IUhaSQGZfjPUj85QqCkZoag2E',
    appId: '1:381116223523:web:a60880979949b98cc3e196',
    messagingSenderId: '381116223523',
    projectId: 'nback1',
    authDomain: 'nback1.firebaseapp.com',
    storageBucket: 'nback1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAASpRviIoX5PdHsjFxxjeNdbC12guaEU',
    appId: '1:381116223523:android:59c4ef16ae44e7e4c3e196',
    messagingSenderId: '381116223523',
    projectId: 'nback1',
    storageBucket: 'nback1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATBO7Da4y5_uKwLWQQa8qQMs1KSKL5WVs',
    appId: '1:381116223523:ios:0470eaac10839d42c3e196',
    messagingSenderId: '381116223523',
    projectId: 'nback1',
    storageBucket: 'nback1.firebasestorage.app',
    iosBundleId: 'com.example.nBack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATBO7Da4y5_uKwLWQQa8qQMs1KSKL5WVs',
    appId: '1:381116223523:ios:0470eaac10839d42c3e196',
    messagingSenderId: '381116223523',
    projectId: 'nback1',
    storageBucket: 'nback1.firebasestorage.app',
    iosBundleId: 'com.example.nBack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDITLtlZ8IUhaSQGZfjPUj85QqCkZoag2E',
    appId: '1:381116223523:web:170ba074e1bf59fcc3e196',
    messagingSenderId: '381116223523',
    projectId: 'nback1',
    authDomain: 'nback1.firebaseapp.com',
    storageBucket: 'nback1.firebasestorage.app',
  );
}
